// Mapping of calculator names to their primary and secondary keyword phrases.
// Generated from user-provided SEO brief to keep keyword usage consistent.
export const MAPPED_KEYWORDS = {
  'Loan Comparison Calculator': ['loan comparison calculator', 'personal loan comparison calculator'],
  'Loan Repayment Calculator': [
    'loan repayment calculator',
    'loan calculator',
    'personal loan calculator',
    'calculate loan payment',
    'loan payment calculator',
    'calculate loan',
    'loan',
    'loan payment',
    'loan payoff calculator',
    'loan payment schedule calculator',
    'loan calculator with extra payments',
    'loan repayment',
    'loan calculator monthly payments',
  ],
  'Mortgage Affordability Calculator': [
    'mortgage affordability calculator',
    'how much mortgage can i afford',
    'mortgage affordability',
  ],
  'Mortgage Calculator': [
    'mortgage calculator',
    'mortgage calculator uk',
    'mortgage loan calculator',
    'mortgage payment calculator',
    'home loan calculator',
    'home mortgage calculator',
    'mortgage',
    'mortgage calculator monthly payments',
    'mortgage interest calculator',
    'mortgage interest',
    'calculate mortgage payment',
    'home loan',
    'loan mortgage calculator',
  ],
  'Mortgage Comparison Calculator': ['mortgage comparison calculator', 'compare mortgage rates'],
  'Mortgage Repayment Calculator': ['mortgage repayment calculator', 'home loan repayment calculator'],
  'Net Income UK Calculator': ['net income uk calculator'],
  'Net Worth Calculator': ['net worth calculator', 'how to calculate net worth'],
  'NI Calculator': ['ni calculator', 'national insurance calculator'],
  'National Insurance Calculator': ['ni calculator', 'national insurance calculator'],
  'Overtime & Bonus Calculator': ['overtime and bonus calculator'],
  'Overtime Pay Calculator': ['overtime pay calculator'],
  'Overtime Rate Calculator': ['overtime rate calculator'],
  'PAYE Calculator': ['paye calculator'],
  'Pension Calculator': [
    'pension calculator',
    'uk pension calculator',
    'private pension calculator',
    'state pension calculator',
    'workplace pension calculator',
  ],
  'Pension Contribution Calculator': [
    'pension contribution calculator',
    'pension contributions calculator',
    'contribution calculator',
  ],
  'Personal Loan Calculator': ['personal loan calculator', 'best personal loan calculator'],
  'Pro Rata Salary Calculator': ['pro rata salary calculator'],
  'Property Flipping Calculator': [
    'property flipping calculator',
    'flip calculator',
    'property renovation calculator',
  ],
  'Property Tax Calculator': [
    'property tax calculator',
    'uk property tax calculator',
    'property tax rates uk',
  ],
  'Redundancy Pay Calculator': ['redundancy pay calculator'],
  'Remortgage Calculator': ['remortgage calculator'],
  'Rental Income Calculator': ['rental income calculator', 'rental income tax calculator'],
  'Rental Yield Calculator': ['rental yield calculator', 'rental yield'],
  'Rent to Buy Calculator': ['rent to buy calculator', 'rent to buy scheme calculator'],
  'Rent vs Buy Calculator': ['rent vs buy calculator', 'rent or buy calculator'],
  'Retirement Calculator': [
    'retirement calculator',
    'retirement income calculator',
    'retirement planning calculator',
  ],
  'Retirement Savings Calculator': ['retirement savings calculator'],
  'Reverse Mortgage Calculator': [
    'reverse mortgage calculator',
    'equity release calculator',
    'lifetime mortgage calculator',
  ],
  'Rule of 72 Calculator': ['rule of 72 calculator'],
  'Salary Calculator': [
    'salary calculator',
    'gross salary calculator',
    'monthly salary calculator',
    'annual salary calculator',
    'yearly salary calculator',
    'hourly salary calculator',
    'weekly salary calculator',
    'daily salary calculator',
  ],
  'Salary Increase Calculator': ['salary increase calculator'],
  'Salary Sacrifice Calculator': ['salary sacrifice calculator'],
  'Savings Goal Calculator': ['savings goal calculator', 'savings calculator', 'savings planner', 'savings'],
  'Severance Pay Calculator': ['severance pay calculator'],
  'Simple Interest Calculator': ['simple interest calculator', 'simple interest'],
  'Stamp Duty Calculator': [
    'stamp duty calculator',
    'stamp duty rates',
    'stamp duty',
    'stamp duty land tax calculator',
    'sdlt calculator',
  ],
  'Statutory Maternity Pay Calculator': ['statutory maternity pay calculator', 'smp calculator'],
  'Statutory Sick Pay Calculator': ['statutory sick pay calculator', 'ssp calculator'],
  'Student Loan Calculator': ['student loan calculator'],
  'Student Loan Repayment Calculator': ['student loan repayment calculator'],
  'Subscription Cost Calculator': ['subscription cost calculator'],
  'Take-Home Pay Calculator': [
    'take home pay calculator',
    'salary take home pay calculator',
    'take home pay',
    'salary after tax calculator',
    'after tax income calculator',
    'take home pay calculator 2024',
    'salary take home',
    'calculate take home pay',
  ],
  'Tax After Tax Calculator': ['tax after tax calculator'],
  'Tax and NI Calculator': ['tax and ni calculator', 'tax and national insurance calculator'],
  'Travel Budget Calculator': ['travel budget calculator'],
  'VAT Calculator': ['vat calculator', 'vat reverse charge calculator'],
  'Wedding Budget Calculator': ['wedding budget calculator'],
  'Minimum Wage Calculator': ['minimum wage calculator', 'national living wage calculator', 'uk minimum wage'],
  'Maternity Pay Calculator': ['maternity pay calculator', 'statutory maternity pay calculator', 'smp calculator'],
};

export const getMappedKeywords = (name) => {
  if (!name) return [];
  const lookup = MAPPED_KEYWORDS[name];
  return Array.isArray(lookup) ? lookup : [];
};
