// src/pages/financial-blueprint/MyMoneyBlueprint.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import paths from '../../paths'; // Import your paths

// You can create this sample report PDF and place it in your /public folder
const SAMPLE_REPORT_URL = '/sample-financial-report.pdf';

const MyMoneyBlueprint = () => {
  return (
    <div className="bg-white">
      <div className="max-w-4xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
        <div className="text-center">
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
            Create Your Financial Blueprint
          </h1>
          <p className="mt-4 text-xl text-gray-600">
            Get a comprehensive, AI-powered analysis of your financial health in minutes.
          </p>
        </div>

        {/* Introduction Section */}
        <div className="mt-12 text-lg text-gray-700 space-y-4">
          <p>
            Understanding your financial standing is the first step toward achieving your goals. Our Financial Blueprint tool goes beyond simple calculations; it provides a holistic overview of your assets, liabilities, and opportunities, all presented in an easy-to-understand report.
          </p>
          <p>
            By answering a series of straightforward questions, you'll receive a personalized report that highlights your strengths, identifies areas for improvement, and offers actionable steps to secure your financial future.
          </p>
        </div>
        
        <div className="mt-10 text-center">
          <p className="text-base font-medium text-gray-600">
            Estimated time to complete: <strong>5-7 minutes</strong>
          </p>
          <div className="mt-6 flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link
              to={paths.financialBlueprintSurvey} // We will add this path next
              className="inline-flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 w-full sm:w-auto"
            >
              Let's Start
            </Link>
            <a
              href={SAMPLE_REPORT_URL}
              download
              className="inline-flex items-center justify-center px-8 py-3 border border-indigo-600 text-base font-medium rounded-md text-indigo-600 bg-white hover:bg-indigo-50 w-full sm:w-auto"
            >
              Download Sample Report
            </a>
          </div>
        </div>

        {/* FAQ Section */}
        <div className="mt-20">
          <h2 className="text-3xl font-bold text-gray-900 text-center">Frequently Asked Questions</h2>
          <div className="mt-8 space-y-8">
            <div>
              <h3 className="text-xl font-semibold text-gray-900">Is my data secure?</h3>
              <p className="mt-2 text-gray-700">
                Absolutely. We do not store any of the personal financial data you enter. All information is processed in real-time to generate your report and is then discarded. Your privacy is our top priority.
              </p>
            </div>
            <div>
              <h3 className="text-xl font-semibold text-gray-900">Is this financial advice?</h3>
              <p className="mt-2 text-gray-700">
                No. This tool is for informational and educational purposes only. The report provides a general analysis based on the data you provide. It is not a substitute for professional financial advice from a qualified advisor.
              </p>
            </div>
          </div>
        </div>

        {/* Disclaimer Section */}
        <div className="mt-20 text-center text-sm text-gray-500">
          <p>
            <strong>Disclaimer:</strong> The information generated by this tool is for illustrative purposes only and should not be considered financial advice. All financial decisions should be made with the guidance of a qualified professional. We are not liable for any actions taken based on the report's content.
          </p>
        </div>
      </div>
    </div>
  );
};

export default MyMoneyBlueprint;
